import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <form method='post' name="contact" netlify > 
      <input type="text" name="name" /> <br /> <br />
      <input type="email" name="email" /> <br /> <br />
      <textarea name="message"></textarea>
    </form>
    </body>
    </html>
  )
}
